export const KIDS = [
  {
    id: "k1", fcbqId: "80316",
    name: "Rohan Thomas", label: "Rohan",
    age: 15, gender: "M",
    shortName: "Cadet ♂",
    competition: "C.C. Cadet Masculí Preferent 1r. Any",
    phase: "Segona Fase — Grup 07",
    usualTime: "16:00",
    kit: { home: { jersey: "NEGRE", shorts: "VERMELL" }, away: { jersey: "BLANCA", shorts: "VERMELL" } },
    color: "#FF6B2B", dimColor: "rgba(255,107,43,0.15)",
    statsAvailable: true,
    statsTeamId: "80316",
    statsTeamName: "C.B GRUP BARNA VERMELL GRUP ESP 1ER ANY",
    competitionResultsId: "21202",
  },
  {
    id: "k2", fcbqId: "81179",
    name: "Sara Thomas", label: "Sara",
    age: 12, gender: "F",
    shortName: "Infantil ♀",
    competition: "C.T. BCN U13 — Infantil Femení 1r. Any Promoció",
    phase: "Segona Fase — Nivell A2 Grup 01",
    usualTime: "12:15",
    kit: { home: { jersey: "NEGRE", shorts: "VERMELL" }, away: { jersey: "BLANCA", shorts: "VERMELL" } },
    color: "#A855F7", dimColor: "rgba(168,85,247,0.15)",
    statsAvailable: false,
  },
];

export const K1_MATCHES = [
  { date:"2025-09-07",  time:"17:45", ha:"away", opp:"CB Granollers 4",              venue:"Pavello C.B. Granollers",           city:"Granollers",            km:30,  played:true,  win:true,  score:"68–55" },
  { date:"2025-09-14",  time:"16:00", ha:"home", opp:"Bàsquet Girona U15",           venue:"Nau Parc Clot",                     city:"Barcelona",             km:0,   played:true,  win:false, score:"61–70" },
  { date:"2025-09-20",  time:"15:30", ha:"away", opp:"JAC Sants Barcelona U15 1",    venue:"CE La Bordeta",                     city:"Barcelona",             km:8,   played:true,  win:true,  score:"74–62" },
  { date:"2025-09-27",  time:"16:00", ha:"home", opp:"Basket Almeda Negre",          venue:"Nau Parc Clot",                     city:"Barcelona",             km:0,   played:true,  win:true,  score:"82–65" },
  { date:"2025-10-05",  time:"12:15", ha:"away", opp:"Motorola CB Sant Josep Badalona","venue":"Pavello La Colina",              city:"Badalona",              km:12,  played:true,  win:false, score:"58–71" },
  { date:"2025-10-12",  time:"16:00", ha:"away", opp:"Nayox Força Lleida B",         venue:"Pavello Barris Nord",               city:"Lleida",                km:162, played:true,  win:true,  score:"77–69" },
  { date:"2025-10-18",  time:"16:00", ha:"home", opp:"UE Montgat Vermell",           venue:"Nau Parc Clot",                     city:"Barcelona",             km:0,   played:true,  win:true,  score:"91–55" },
  { date:"2025-10-25",  time:"16:00", ha:"home", opp:"CB Granollers 4",              venue:"Nau Parc Clot",                     city:"Barcelona",             km:0,   played:true,  win:false, score:"60–66" },
  { date:"2025-11-01",  time:"16:00", ha:"away", opp:"Bàsquet Girona U15",           venue:"Pavelló St Eugènia",                city:"Girona",                km:103, played:true,  win:true,  score:"72–68" },
  { date:"2025-11-09",  time:"17:45", ha:"home", opp:"JAC Sants Barcelona U15 1",   venue:"Nau Parc Clot",                     city:"Barcelona",             km:0,   played:true,  win:true,  score:"85–70" },
  { date:"2025-11-16",  time:"16:30", ha:"away", opp:"Basket Almeda Negre",         venue:"Pavello Almeda",                    city:"Cornellà de Llobregat", km:14,  played:true,  win:false, score:"55–62" },
  { date:"2025-11-22",  time:"16:00", ha:"home", opp:"Motorola CB Sant Josep Badalona","venue":"Nau Parc Clot",                 city:"Barcelona",             km:0,   played:true,  win:true,  score:"80–71" },
  { date:"2025-11-30",  time:"17:45", ha:"home", opp:"Nayox Força Lleida B",        venue:"Nau Parc Clot",                     city:"Barcelona",             km:0,   played:true,  win:true,  score:"88–64" },
  { date:"2025-12-13",  time:"12:15", ha:"away", opp:"UE Montgat Vermell",           venue:"Poliesp. Silvia Domínguez",         city:"Montgat",               km:18,  played:true,  win:true,  score:"76–58" },
  { date:"2026-01-10",  time:"16:00", ha:"home", opp:"CB Viladecans Blanc",          venue:"Nau Parc Clot",                     city:"Barcelona",             km:0,   played:true,  win:false, score:"69–74" },
  { date:"2026-01-17",  time:"12:30", ha:"away", opp:"CB Calella 1r Any",            venue:"Pavello Municipal Calella",         city:"Calella",               km:63,  played:true,  win:true,  score:"81–72" },
  { date:"2026-01-25",  time:"17:45", ha:"home", opp:"UE Sant Cugat – Occident 2011",venue:"Nau Parc Clot",                    city:"Barcelona",             km:0,   played:true,  win:true,  score:"79–65" },
  { date:"2026-01-31",  time:"12:45", ha:"away", opp:"TGN Bàsquet 11A",              venue:"Col. Sagrat Cor",                   city:"Tarragona",             km:99,  played:true,  win:false, score:"62–78" },
  { date:"2026-02-07",  time:"16:00", ha:"home", opp:"La Salle Manresa 1",           venue:"Nau Parc Clot",                     city:"Barcelona",             km:0,   played:true,  win:true,  score:"88–76" },
  { date:"2026-03-01",  time:"12:30", ha:"away", opp:"Carnisseries Soler BBA Castelldefels","venue":"Complex Can Vinader",      city:"Castelldefels",         km:24,  played:true,  win:true,  score:"71–65" },
  { date:"2026-03-07",  time:"19:30", ha:"away", opp:"CB Viladecans Blanc",          venue:"Col·legi Sant Gabriel",             city:"Viladecans",            km:22,  played:false },
  { date:"2026-03-14",  time:"16:00", ha:"home", opp:"CB Calella 1r Any",            venue:"Nau Parc Clot",                     city:"Barcelona",             km:0,   played:false },
  { date:"2026-03-21",  time:"10:30", ha:"away", opp:"UE Sant Cugat – Occident 2011",venue:"Institut Leonardo Da Vinci",        city:"Sant Cugat del Vallès", km:25,  played:false, canvis:true },
  { date:"2026-03-28",  time:"10:45", ha:"home", opp:"CB Guíxols U15",               venue:"Nau Parc Clot",                     city:"Barcelona",             km:0,   played:false, canvis:true },
  { date:"2026-04-11",  time:"16:00", ha:"home", opp:"TGN Bàsquet 11A",              venue:"Nau Parc Clot",                     city:"Barcelona",             km:0,   played:false },
  { date:"2026-04-19",  time:"16:00", ha:"away", opp:"La Salle Manresa 1",           venue:"Col·legi La Salle Manresa",         city:"Manresa",               km:75,  played:false, canvis:true },
  { date:"2026-04-26",  time:"10:45", ha:"away", opp:"CB Guíxols U15",               venue:"Pavello La Corchera",               city:"Sant Feliu de Guíxols", km:105, played:false },
  { date:"2026-05-09",  time:"16:00", ha:"home", opp:"Carnisseries Soler BBA Castelldefels","venue":"Nau Parc Clot",            city:"Barcelona",             km:0,   played:false },
];

export const K2_MATCHES = [
  { date:"2025-10-04",  time:"12:15", ha:"home", opp:"Lluïsos de Gràcia",             venue:"Nau Parc Clot",                     city:"Barcelona",             km:0,   played:true },
  { date:"2025-10-12",  time:"09:00", ha:"away", opp:"C.B. Prat-Montibello B",        venue:"Cem Estruch",                       city:"El Prat de Llobregat",  km:14,  played:true },
  { date:"2025-10-19",  time:"10:45", ha:"home", opp:"UE Sant Cugat-Occident 2013",   venue:"Nau Parc Clot",                     city:"Barcelona",             km:0,   played:true },
  { date:"2025-10-25",  time:"10:00", ha:"away", opp:"CB Sant Just U13 Blau",         venue:"Pavelló La Bonaigua",               city:"Sant Just Desvern",     km:9,   played:true },
  { date:"2025-11-08",  time:"12:15", ha:"home", opp:"U.E. Claret B",                 venue:"Nau Parc Clot",                     city:"Barcelona",             km:0,   played:true },
  { date:"2025-11-16",  time:"10:45", ha:"away", opp:"Lluïsos de Gràcia",             venue:"Plaça del Nord",                    city:"Barcelona",             km:5,   played:true },
  { date:"2025-11-22",  time:"12:15", ha:"home", opp:"C.B. Prat-Montibello B",        venue:"Nau Parc Clot",                     city:"Barcelona",             km:0,   played:true },
  { date:"2025-11-29",  time:"12:00", ha:"away", opp:"UE Sant Cugat-Occident 2013",   venue:"Institut Leonardo da Vinci",        city:"Sant Cugat del Vallès", km:25,  played:true },
  { date:"2025-12-13",  time:"12:15", ha:"home", opp:"CB Sant Just U13 Blau",         venue:"Nau Parc Clot",                     city:"Barcelona",             km:0,   played:true },
  { date:"2025-12-23",  time:"18:00", ha:"away", opp:"U.E. Claret B",                 venue:"Col·legi Claret",                   city:"Barcelona",             km:4,   played:true },
  { date:"2026-01-17",  time:"12:15", ha:"away", opp:"Talenom Boet Mataró Taronja",   venue:"Poliesportiu Eusebio Millan",       city:"Mataró",                km:30,  played:true },
  { date:"2026-01-24",  time:"12:15", ha:"home", opp:"Basket Almeda Groc",            venue:"Nau Parc Clot",                     city:"Barcelona",             km:0,   played:true },
  { date:"2026-01-31",  time:"12:00", ha:"away", opp:"UE Sant Cugat-Occident 2013",   venue:"Institut Leonardo da Vinci",        city:"Sant Cugat del Vallès", km:25,  played:true },
  { date:"2026-02-07",  time:"12:15", ha:"home", opp:"C.B. Prat-Montibello B",        venue:"Nau Parc Clot",                     city:"Barcelona",             km:0,   played:true },
  { date:"2026-02-21",  time:"12:15", ha:"home", opp:"CB Artés",                      venue:"Nau Parc Clot",                     city:"Barcelona",             km:0,   played:true },
  { date:"2026-03-01",  time:"09:00", ha:"away", opp:"C.B. Vilassar de Mar 1984 Verd",venue:"Pavelló La Bobila",                 city:"Vilassar de Mar",       km:27,  played:true },
  { date:"2026-03-07",  time:"12:15", ha:"home", opp:"CB Parets Vermell 1",           venue:"Nau Parc Clot",                     city:"Barcelona",             km:0,   played:false },
  { date:"2026-03-14",  time:"12:15", ha:"home", opp:"Talenom Boet Mataró Taronja",   venue:"Nau Parc Clot",                     city:"Barcelona",             km:0,   played:false },
  { date:"2026-03-21",  time:"13:30", ha:"away", opp:"Basket Almeda Groc",            venue:"Pavelló Almeda",                    city:"Cornellà de Llobregat", km:14,  played:false },
  { date:"2026-04-11",  time:"12:15", ha:"home", opp:"UE Sant Cugat-Occident 2013",   venue:"Nau Parc Clot",                     city:"Barcelona",             km:0,   played:false },
  { date:"2026-04-18",  time:"10:45", ha:"away", opp:"C.B. Prat-Montibello B",        venue:"Cem Estruch",                       city:"El Prat de Llobregat",  km:14,  played:false },
  { date:"2026-04-25",  time:"12:30", ha:"away", opp:"CB Artés",                      venue:"Pavelló Esportiu d'Artés",          city:"Artés",                 km:68,  played:false },
  { date:"2026-05-09",  time:"12:15", ha:"home", opp:"C.B. Vilassar de Mar 1984 Verd",venue:"Nau Parc Clot",                     city:"Barcelona",             km:0,   played:false },
  { date:"2026-05-16",  time:"10:45", ha:"away", opp:"CB Parets Vermell 1",           venue:"Pavelló Municipal Parets",          city:"Parets del Vallès",     km:23,  played:false },
];

export const CHECKLIST_STD = [
  { id:"jersey",  emoji:"👕", label:"Match Jersey" },
  { id:"shorts",  emoji:"🩳", label:"Match Shorts" },
  { id:"shoes",   emoji:"👟", label:"Basketball Shoes" },
  { id:"water",   emoji:"💧", label:"Water Bottle (full)" },
  { id:"snack",   emoji:"🍌", label:"Pre-match Snack" },
  { id:"fedcard", emoji:"🪪", label:"Federació ID Card ⚠️" },
  { id:"towel",   emoji:"🧺", label:"Towel" },
  { id:"bag",     emoji:"🎒", label:"Kit Bag" },
];

export const CHECKLIST_ROAD = [
  { id:"jersey",  emoji:"👕", label:"Away Jersey (BLANCA)" },
  { id:"shorts",  emoji:"🩳", label:"Match Shorts (VERMELL)" },
  { id:"shoes",   emoji:"👟", label:"Basketball Shoes" },
  { id:"water",   emoji:"💧", label:"Large Water Bottle" },
  { id:"snack",   emoji:"🍱", label:"Road Snacks (2h trip)" },
  { id:"fedcard", emoji:"🪪", label:"Federació ID Card ⚠️" },
  { id:"towel",   emoji:"🧺", label:"Towel" },
  { id:"layer",   emoji:"🧥", label:"Extra Layer / Hoodie" },
  { id:"cash",    emoji:"💶", label:"Cash — Food Stop" },
  { id:"charger", emoji:"🔋", label:"Phone Charger" },
  { id:"bag",     emoji:"🎒", label:"Kit Bag" },
];
