export const darkTheme = {
  bg:           "#070912",
  cardBg:       "#111827",
  cardBgDeep:   "#0d1420",
  cardBorder:   "rgba(255,255,255,0.07)",
  textPrimary:  "#e2e8f0",
  textSecondary:"#475569",
  textMuted:    "#334155",
  textDim:      "#64748b",
  textSubtle:   "#94a3b8",
  divider:      "rgba(255,255,255,0.05)",
  tabBorder:    "rgba(255,255,255,0.07)",
  inputBg:      "#0f172a",
  inputBorder:  "rgba(255,255,255,0.1)",
  heroGradient: "linear-gradient(135deg, #111827 0%, #1a2035 100%)",
  roadGradient: "linear-gradient(135deg, #111827, #1a160a)",
  textBright:   "#f1f5f9",
  cardAlt:      "#0f172a",
  rowBg:        "rgba(255,255,255,0.03)",
  rowBorder:    "rgba(255,255,255,0.04)",
};

export const lightTheme = {
  bg:           "#f8fafc",
  cardBg:       "#ffffff",
  cardBgDeep:   "#f1f5f9",
  cardBorder:   "rgba(0,0,0,0.08)",
  textPrimary:  "#0f172a",
  textSecondary:"#334155",
  textMuted:    "#64748b",
  textDim:      "#475569",
  textSubtle:   "#334155",
  divider:      "rgba(0,0,0,0.06)",
  tabBorder:    "rgba(0,0,0,0.08)",
  inputBg:      "#f1f5f9",
  inputBorder:  "rgba(0,0,0,0.12)",
  heroGradient: "linear-gradient(135deg, #ffffff 0%, #f0f4ff 100%)",
  roadGradient: "linear-gradient(135deg, #ffffff, #fffbf5)",
  textBright:   "#0f172a",
  cardAlt:      "#ffffff",
  rowBg:        "rgba(0,0,0,0.025)",
  rowBorder:    "rgba(0,0,0,0.06)",
};

export function makeStyles(theme) {
  return {
    app: {
      fontFamily: "'DM Sans', system-ui, sans-serif",
      backgroundColor: theme.bg,
      color: theme.textPrimary,
      minHeight: "100vh",
      maxWidth: 520,
      margin: "0 auto",
      position: "relative",
    },
    header: {
      padding: "max(20px, env(safe-area-inset-top)) 20px 0",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
    },
    logo: {
      fontFamily: "'Barlow Condensed', system-ui, sans-serif",
      fontSize: 32,
      fontWeight: 800,
      letterSpacing: "0.05em",
      color: "#FF6B2B",
      lineHeight: 1,
    },
    subtitle: {
      fontSize: 12, color: theme.textSecondary,
      letterSpacing: "0.12em", textTransform: "uppercase", marginTop: 2,
    },
    tabBar: {
      display: "flex",
      borderBottom: `1px solid ${theme.tabBorder}`,
      margin: "16px 0 0",
      padding: "0 20px",
      gap: 4,
      overflowX: "auto",
    },
    tab: (active, color = "#FF6B2B") => ({
      background: "none",
      border: "none",
      borderBottom: active ? `2px solid ${color}` : "2px solid transparent",
      color: active ? color : theme.textSecondary,
      cursor: "pointer",
      padding: "12px 14px 10px",
      fontFamily: "'DM Sans', sans-serif",
      fontSize: 14,
      fontWeight: 500,
      whiteSpace: "nowrap",
      transition: "color 0.2s",
      flexShrink: 0,
    }),
    body: { padding: "20px" },
    card: (extra = {}) => ({
      background: theme.cardBg,
      border: `1px solid ${theme.cardBorder}`,
      borderRadius: 12,
      padding: 16,
      marginBottom: 12,
      ...extra,
    }),
    heroCard: {
      background: theme.heroGradient,
      border: "1px solid rgba(255,107,43,0.25)",
      borderRadius: 16,
      padding: 20,
      marginBottom: 16,
      position: "relative",
      overflow: "hidden",
    },
    roadCard: {
      background: theme.roadGradient,
      border: "1px solid rgba(255,179,71,0.3)",
      borderRadius: 12,
      padding: 16,
      marginBottom: 12,
    },
    label: {
      fontSize: 10, letterSpacing: "0.12em",
      textTransform: "uppercase", color: theme.textSecondary, marginBottom: 4,
    },
    sectionTitle: {
      fontFamily: "'Barlow Condensed', sans-serif",
      fontSize: 18, fontWeight: 700, letterSpacing: "0.04em",
      color: theme.textSubtle, textTransform: "uppercase",
      marginBottom: 12, marginTop: 4,
    },
    spaceBetween: { display: "flex", alignItems: "center", justifyContent: "space-between" },
    row: { display: "flex", alignItems: "center", gap: 8 },
    divider: { height: 1, background: theme.divider, margin: "12px 0" },
    badge: (type) => {
      const map = {
        home:   { bg: "rgba(34,211,160,0.12)",  color: "#22d3a0", border: "rgba(34,211,160,0.25)" },
        away:   { bg: "rgba(255,71,87,0.12)",   color: "#ff4757", border: "rgba(255,71,87,0.25)" },
        road:   { bg: "rgba(255,179,71,0.12)",  color: "#ffb347", border: "rgba(255,179,71,0.3)" },
        local:  { bg: "rgba(255,71,87,0.12)",   color: "#ff4757", border: "rgba(255,71,87,0.25)" },
        metro:  { bg: "rgba(255,71,87,0.12)",   color: "#ff4757", border: "rgba(255,71,87,0.25)" },
        canvis: { bg: "rgba(250,204,21,0.12)",  color: "#facc15", border: "rgba(250,204,21,0.3)" },
        k1:     { bg: "rgba(255,107,43,0.12)",  color: "#FF6B2B", border: "rgba(255,107,43,0.25)" },
        k2:     { bg: "rgba(168,85,247,0.12)",  color: "#a855f7", border: "rgba(168,85,247,0.25)" },
        k3:     { bg: "rgba(20,184,166,0.12)",  color: "#14b8a6", border: "rgba(20,184,166,0.25)" },
      };
      const c = map[type] || map.home;
      return {
        display: "inline-flex", alignItems: "center",
        background: c.bg, color: c.color,
        border: `1px solid ${c.border}`,
        borderRadius: 6, padding: "2px 8px",
        fontSize: 12, fontWeight: 600, letterSpacing: "0.06em",
        textTransform: "uppercase",
      };
    },
    statBox: {
      background: theme.cardBg,
      border: `1px solid ${theme.cardBorder}`,
      borderRadius: 10, padding: "12px 16px", textAlign: "center", flex: 1,
    },
    statNum: {
      fontFamily: "'Barlow Condensed', sans-serif",
      fontSize: 32, fontWeight: 700, lineHeight: 1,
    },
    statLbl: {
      fontSize: 11, letterSpacing: "0.1em",
      color: theme.textSecondary, textTransform: "uppercase", marginTop: 2,
    },
    checkItem: (checked) => ({
      display: "flex", alignItems: "center", gap: 12,
      padding: "9px 12px", borderRadius: 8, cursor: "pointer",
      opacity: checked ? 0.4 : 1,
      transition: "opacity 0.2s",
      background: checked ? "rgba(255,255,255,0.02)" : "transparent",
    }),
    checkBox: (checked) => ({
      width: 20, height: 20, borderRadius: 5, flexShrink: 0,
      border: checked ? "2px solid #FF6B2B" : `2px solid ${theme.textMuted}`,
      background: checked ? "#FF6B2B" : "transparent",
      display: "flex", alignItems: "center", justifyContent: "center",
      transition: "all 0.15s",
      fontSize: 11, color: "white",
    }),
    mapsBtn: {
      display: "inline-flex", alignItems: "center", gap: 6,
      background: "rgba(255,107,43,0.1)", color: "#FF6B2B",
      border: "1px solid rgba(255,107,43,0.25)", borderRadius: 8,
      padding: "7px 14px", fontSize: 12, fontWeight: 500,
      cursor: "pointer", textDecoration: "none",
    },
    primaryBtn: {
      background: "linear-gradient(135deg, #FF6B2B, #e55c20)",
      color: "white", border: "none", borderRadius: 8,
      padding: "10px 16px", fontSize: 13, fontWeight: 600,
      cursor: "pointer", width: "100%",
    },
    kidBtn: (active, color) => ({
      flex: 1,
      background: active ? color : theme.cardBg,
      border: `1px solid ${active ? color : theme.cardBorder}`,
      borderRadius: 8, padding: "8px 12px", cursor: "pointer",
      color: active ? "white" : theme.textDim, fontSize: 13, fontWeight: 500,
      transition: "all 0.15s",
    }),
  };
}
